// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/grpc-client/proto/voting.proto

package voting;

public final class VotingOuterClass {
    private VotingOuterClass() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface VotingRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:voting.VotingRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string url = 1;</code>
         * @return The url.
         */
        java.lang.String getUrl();
        /**
         * <code>string url = 1;</code>
         * @return The bytes for url.
         */
        com.google.protobuf.ByteString
        getUrlBytes();

        /**
         * <code>.voting.VotingRequest.Vote vote = 2;</code>
         * @return The enum numeric value on the wire for vote.
         */
        int getVoteValue();
        /**
         * <code>.voting.VotingRequest.Vote vote = 2;</code>
         * @return The vote.
         */
        voting.VotingOuterClass.VotingRequest.Vote getVote();
    }
    /**
     * Protobuf type {@code voting.VotingRequest}
     */
    public static final class VotingRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:voting.VotingRequest)
            VotingRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use VotingRequest.newBuilder() to construct.
        private VotingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private VotingRequest() {
            url_ = "";
            vote_ = 0;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new VotingRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private VotingRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            url_ = s;
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();

                            vote_ = rawValue;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return voting.VotingOuterClass.internal_static_voting_VotingRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return voting.VotingOuterClass.internal_static_voting_VotingRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            voting.VotingOuterClass.VotingRequest.class, voting.VotingOuterClass.VotingRequest.Builder.class);
        }

        /**
         * Protobuf enum {@code voting.VotingRequest.Vote}
         */
        public enum Vote
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>UP = 0;</code>
             */
            UP(0),
            /**
             * <code>DOWN = 1;</code>
             */
            DOWN(1),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>UP = 0;</code>
             */
            public static final int UP_VALUE = 0;
            /**
             * <code>DOWN = 1;</code>
             */
            public static final int DOWN_VALUE = 1;


            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Vote valueOf(int value) {
                return forNumber(value);
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             */
            public static Vote forNumber(int value) {
                switch (value) {
                    case 0: return UP;
                    case 1: return DOWN;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Vote>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Vote> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Vote>() {
                        public Vote findValueByNumber(int number) {
                            return Vote.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalStateException(
                            "Can't get the descriptor of an unrecognized enum value.");
                }
                return getDescriptor().getValues().get(ordinal());
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return voting.VotingOuterClass.VotingRequest.getDescriptor().getEnumTypes().get(0);
            }

            private static final Vote[] VALUES = values();

            public static Vote valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private Vote(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:voting.VotingRequest.Vote)
        }

        public static final int URL_FIELD_NUMBER = 1;
        private volatile java.lang.Object url_;
        /**
         * <code>string url = 1;</code>
         * @return The url.
         */
        @java.lang.Override
        public java.lang.String getUrl() {
            java.lang.Object ref = url_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                url_ = s;
                return s;
            }
        }
        /**
         * <code>string url = 1;</code>
         * @return The bytes for url.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUrlBytes() {
            java.lang.Object ref = url_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                url_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int VOTE_FIELD_NUMBER = 2;
        private int vote_;
        /**
         * <code>.voting.VotingRequest.Vote vote = 2;</code>
         * @return The enum numeric value on the wire for vote.
         */
        @java.lang.Override public int getVoteValue() {
            return vote_;
        }
        /**
         * <code>.voting.VotingRequest.Vote vote = 2;</code>
         * @return The vote.
         */
        @java.lang.Override public voting.VotingOuterClass.VotingRequest.Vote getVote() {
            @SuppressWarnings("deprecation")
            voting.VotingOuterClass.VotingRequest.Vote result = voting.VotingOuterClass.VotingRequest.Vote.valueOf(vote_);
            return result == null ? voting.VotingOuterClass.VotingRequest.Vote.UNRECOGNIZED : result;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getUrlBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
            }
            if (vote_ != voting.VotingOuterClass.VotingRequest.Vote.UP.getNumber()) {
                output.writeEnum(2, vote_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getUrlBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
            }
            if (vote_ != voting.VotingOuterClass.VotingRequest.Vote.UP.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, vote_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof voting.VotingOuterClass.VotingRequest)) {
                return super.equals(obj);
            }
            voting.VotingOuterClass.VotingRequest other = (voting.VotingOuterClass.VotingRequest) obj;

            if (!getUrl()
                    .equals(other.getUrl())) return false;
            if (vote_ != other.vote_) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + URL_FIELD_NUMBER;
            hash = (53 * hash) + getUrl().hashCode();
            hash = (37 * hash) + VOTE_FIELD_NUMBER;
            hash = (53 * hash) + vote_;
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static voting.VotingOuterClass.VotingRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static voting.VotingOuterClass.VotingRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static voting.VotingOuterClass.VotingRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(voting.VotingOuterClass.VotingRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code voting.VotingRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:voting.VotingRequest)
                voting.VotingOuterClass.VotingRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return voting.VotingOuterClass.internal_static_voting_VotingRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return voting.VotingOuterClass.internal_static_voting_VotingRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                voting.VotingOuterClass.VotingRequest.class, voting.VotingOuterClass.VotingRequest.Builder.class);
            }

            // Construct using voting.VotingOuterClass.VotingRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                url_ = "";

                vote_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return voting.VotingOuterClass.internal_static_voting_VotingRequest_descriptor;
            }

            @java.lang.Override
            public voting.VotingOuterClass.VotingRequest getDefaultInstanceForType() {
                return voting.VotingOuterClass.VotingRequest.getDefaultInstance();
            }

            @java.lang.Override
            public voting.VotingOuterClass.VotingRequest build() {
                voting.VotingOuterClass.VotingRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public voting.VotingOuterClass.VotingRequest buildPartial() {
                voting.VotingOuterClass.VotingRequest result = new voting.VotingOuterClass.VotingRequest(this);
                result.url_ = url_;
                result.vote_ = vote_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof voting.VotingOuterClass.VotingRequest) {
                    return mergeFrom((voting.VotingOuterClass.VotingRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(voting.VotingOuterClass.VotingRequest other) {
                if (other == voting.VotingOuterClass.VotingRequest.getDefaultInstance()) return this;
                if (!other.getUrl().isEmpty()) {
                    url_ = other.url_;
                    onChanged();
                }
                if (other.vote_ != 0) {
                    setVoteValue(other.getVoteValue());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                voting.VotingOuterClass.VotingRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (voting.VotingOuterClass.VotingRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object url_ = "";
            /**
             * <code>string url = 1;</code>
             * @return The url.
             */
            public java.lang.String getUrl() {
                java.lang.Object ref = url_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    url_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string url = 1;</code>
             * @return The bytes for url.
             */
            public com.google.protobuf.ByteString
            getUrlBytes() {
                java.lang.Object ref = url_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    url_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string url = 1;</code>
             * @param value The url to set.
             * @return This builder for chaining.
             */
            public Builder setUrl(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                url_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string url = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearUrl() {

                url_ = getDefaultInstance().getUrl();
                onChanged();
                return this;
            }
            /**
             * <code>string url = 1;</code>
             * @param value The bytes for url to set.
             * @return This builder for chaining.
             */
            public Builder setUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                url_ = value;
                onChanged();
                return this;
            }

            private int vote_ = 0;
            /**
             * <code>.voting.VotingRequest.Vote vote = 2;</code>
             * @return The enum numeric value on the wire for vote.
             */
            @java.lang.Override public int getVoteValue() {
                return vote_;
            }
            /**
             * <code>.voting.VotingRequest.Vote vote = 2;</code>
             * @param value The enum numeric value on the wire for vote to set.
             * @return This builder for chaining.
             */
            public Builder setVoteValue(int value) {

                vote_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>.voting.VotingRequest.Vote vote = 2;</code>
             * @return The vote.
             */
            @java.lang.Override
            public voting.VotingOuterClass.VotingRequest.Vote getVote() {
                @SuppressWarnings("deprecation")
                voting.VotingOuterClass.VotingRequest.Vote result = voting.VotingOuterClass.VotingRequest.Vote.valueOf(vote_);
                return result == null ? voting.VotingOuterClass.VotingRequest.Vote.UNRECOGNIZED : result;
            }
            /**
             * <code>.voting.VotingRequest.Vote vote = 2;</code>
             * @param value The vote to set.
             * @return This builder for chaining.
             */
            public Builder setVote(voting.VotingOuterClass.VotingRequest.Vote value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                vote_ = value.getNumber();
                onChanged();
                return this;
            }
            /**
             * <code>.voting.VotingRequest.Vote vote = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearVote() {

                vote_ = 0;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:voting.VotingRequest)
        }

        // @@protoc_insertion_point(class_scope:voting.VotingRequest)
        private static final voting.VotingOuterClass.VotingRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new voting.VotingOuterClass.VotingRequest();
        }

        public static voting.VotingOuterClass.VotingRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<VotingRequest>
                PARSER = new com.google.protobuf.AbstractParser<VotingRequest>() {
            @java.lang.Override
            public VotingRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new VotingRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<VotingRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<VotingRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public voting.VotingOuterClass.VotingRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface VotingResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:voting.VotingResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string confirmation = 1;</code>
         * @return The confirmation.
         */
        java.lang.String getConfirmation();
        /**
         * <code>string confirmation = 1;</code>
         * @return The bytes for confirmation.
         */
        com.google.protobuf.ByteString
        getConfirmationBytes();
    }
    /**
     * Protobuf type {@code voting.VotingResponse}
     */
    public static final class VotingResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:voting.VotingResponse)
            VotingResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use VotingResponse.newBuilder() to construct.
        private VotingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private VotingResponse() {
            confirmation_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new VotingResponse();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private VotingResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            confirmation_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return voting.VotingOuterClass.internal_static_voting_VotingResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return voting.VotingOuterClass.internal_static_voting_VotingResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            voting.VotingOuterClass.VotingResponse.class, voting.VotingOuterClass.VotingResponse.Builder.class);
        }

        public static final int CONFIRMATION_FIELD_NUMBER = 1;
        private volatile java.lang.Object confirmation_;
        /**
         * <code>string confirmation = 1;</code>
         * @return The confirmation.
         */
        @java.lang.Override
        public java.lang.String getConfirmation() {
            java.lang.Object ref = confirmation_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                confirmation_ = s;
                return s;
            }
        }
        /**
         * <code>string confirmation = 1;</code>
         * @return The bytes for confirmation.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getConfirmationBytes() {
            java.lang.Object ref = confirmation_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                confirmation_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getConfirmationBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, confirmation_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getConfirmationBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, confirmation_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof voting.VotingOuterClass.VotingResponse)) {
                return super.equals(obj);
            }
            voting.VotingOuterClass.VotingResponse other = (voting.VotingOuterClass.VotingResponse) obj;

            if (!getConfirmation()
                    .equals(other.getConfirmation())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CONFIRMATION_FIELD_NUMBER;
            hash = (53 * hash) + getConfirmation().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static voting.VotingOuterClass.VotingResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static voting.VotingOuterClass.VotingResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static voting.VotingOuterClass.VotingResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(voting.VotingOuterClass.VotingResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code voting.VotingResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:voting.VotingResponse)
                voting.VotingOuterClass.VotingResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return voting.VotingOuterClass.internal_static_voting_VotingResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return voting.VotingOuterClass.internal_static_voting_VotingResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                voting.VotingOuterClass.VotingResponse.class, voting.VotingOuterClass.VotingResponse.Builder.class);
            }

            // Construct using voting.VotingOuterClass.VotingResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                confirmation_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return voting.VotingOuterClass.internal_static_voting_VotingResponse_descriptor;
            }

            @java.lang.Override
            public voting.VotingOuterClass.VotingResponse getDefaultInstanceForType() {
                return voting.VotingOuterClass.VotingResponse.getDefaultInstance();
            }

            @java.lang.Override
            public voting.VotingOuterClass.VotingResponse build() {
                voting.VotingOuterClass.VotingResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public voting.VotingOuterClass.VotingResponse buildPartial() {
                voting.VotingOuterClass.VotingResponse result = new voting.VotingOuterClass.VotingResponse(this);
                result.confirmation_ = confirmation_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof voting.VotingOuterClass.VotingResponse) {
                    return mergeFrom((voting.VotingOuterClass.VotingResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(voting.VotingOuterClass.VotingResponse other) {
                if (other == voting.VotingOuterClass.VotingResponse.getDefaultInstance()) return this;
                if (!other.getConfirmation().isEmpty()) {
                    confirmation_ = other.confirmation_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                voting.VotingOuterClass.VotingResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (voting.VotingOuterClass.VotingResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object confirmation_ = "";
            /**
             * <code>string confirmation = 1;</code>
             * @return The confirmation.
             */
            public java.lang.String getConfirmation() {
                java.lang.Object ref = confirmation_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    confirmation_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string confirmation = 1;</code>
             * @return The bytes for confirmation.
             */
            public com.google.protobuf.ByteString
            getConfirmationBytes() {
                java.lang.Object ref = confirmation_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    confirmation_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string confirmation = 1;</code>
             * @param value The confirmation to set.
             * @return This builder for chaining.
             */
            public Builder setConfirmation(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                confirmation_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string confirmation = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearConfirmation() {

                confirmation_ = getDefaultInstance().getConfirmation();
                onChanged();
                return this;
            }
            /**
             * <code>string confirmation = 1;</code>
             * @param value The bytes for confirmation to set.
             * @return This builder for chaining.
             */
            public Builder setConfirmationBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                confirmation_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:voting.VotingResponse)
        }

        // @@protoc_insertion_point(class_scope:voting.VotingResponse)
        private static final voting.VotingOuterClass.VotingResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new voting.VotingOuterClass.VotingResponse();
        }

        public static voting.VotingOuterClass.VotingResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<VotingResponse>
                PARSER = new com.google.protobuf.AbstractParser<VotingResponse>() {
            @java.lang.Override
            public VotingResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new VotingResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<VotingResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<VotingResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public voting.VotingOuterClass.VotingResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_voting_VotingRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_voting_VotingRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_voting_VotingResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_voting_VotingResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\"src/grpc-client/proto/voting.proto\022\006vo" +
                        "ting\"`\n\rVotingRequest\022\013\n\003url\030\001 \001(\t\022(\n\004vo" +
                        "te\030\002 \001(\0162\032.voting.VotingRequest.Vote\"\030\n\004" +
                        "Vote\022\006\n\002UP\020\000\022\010\n\004DOWN\020\001\"&\n\016VotingResponse" +
                        "\022\024\n\014confirmation\030\001 \001(\t2?\n\006Voting\0225\n\004Vote" +
                        "\022\025.voting.VotingRequest\032\026.voting.VotingR" +
                        "esponseb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_voting_VotingRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_voting_VotingRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_voting_VotingRequest_descriptor,
                new java.lang.String[] { "Url", "Vote", });
        internal_static_voting_VotingResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_voting_VotingResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_voting_VotingResponse_descriptor,
                new java.lang.String[] { "Confirmation", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
